name: Przemysław Świderski's blog
about: >
  ![Profile pic](assets/profilePic.PNG "It is me :)")


  My name is Przemysław Świderski.
  I am working as Software Developer.


  My LinkedIn [profile](https://www.linkedin.com/in/przemysław-świderski-12b296102).


  In this blog I would like to write about different problems which I encountered during my programming experience.

master_repo: false
url: "http://PrzemyslawSwiderski.github.io"
markdown: kramdown
highlighter: rouge

plugins_dir: ['jekyll-paginate', 'jekyll-gist']

paginate: 3

logo:             logo.png
disqus_shortname: PrzemyslawSwiderski

owner:
  name:           PrzemyslawSwiderski
  avatar:         ""
  email:          "przemyslaw.swiderski7@gmail.com"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
# Gems
gems: [jekyll-paginate]
theme: jekyll-theme-midnight