name: Przemysław Świderski's blog
about: >
  ![Profile pic](assets/profilePic.PNG "It is me :)")


  My name is Przemysław Świderski.
  I am working as Software Developer.


  My LinkedIn [profile](https://www.linkedin.com/in/przemysław-świderski-12b296102).


  In this blog I would like to write about different problems which I encountered during my programming experience.

master_repo: false
url: "https://PrzemyslawSwiderski.github.io"
markdown: kramdown
highlighter: rouge

plugins:
  - "jekyll-paginate"

paginate: 5 # How many items have to be displayed on page

logo:             logo.png
disqus_shortname: githubblog-8

owner:
  name:           PrzemyslawSwiderski
  avatar:         ""
  email:          "przemyslaw.swiderski7@gmail.com"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
# Gems
gems: [jekyll-paginate]